# Generated by Django 5.0 on 2024-01-12 13:09

import base_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0006_alter_applicationuser_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicles",
            fields=[
                (
                    "reference_id",
                    models.CharField(
                        default=base_app.models.generate_uuid,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("data_generated_on", models.DateTimeField(auto_now_add=True)),
                ("vehicle_name", models.CharField(max_length=32)),
                ("vehicle_desc", models.TextField(blank=True, null=True)),
                ("vehicle_company", models.CharField(max_length=30)),
                ("vehicle_type", models.CharField(max_length=15)),
                ("vehicle_seater", models.PositiveSmallIntegerField()),
                ("vehicle_number_plate", models.CharField(max_length=15, unique=True)),
                (
                    "vehicle_documents",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("can_be_listed", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_app.renteruser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
