# Generated by Django 5.0 on 2024-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0007_vehicles"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicles",
            name="vehicle_description_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
