# Generated by Django 5.0 on 2024-01-12 13:51

import base_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0008_vehicles_vehicle_description_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleListingRequests",
            fields=[
                (
                    "reference_id",
                    models.CharField(
                        default=base_app.models.generate_uuid,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("data_generated_on", models.DateTimeField(auto_now_add=True)),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_app.vehicles",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
