# Generated by Django 5.0 on 2024-01-15 13:57

import base_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0009_vehiclelistingrequests"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleListingResult",
            fields=[
                (
                    "reference_id",
                    models.CharField(
                        default=base_app.models.generate_uuid,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("data_generated_on", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField()),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_app.adminuser",
                    ),
                ),
                (
                    "vehicle_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_app.vehiclelistingrequests",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
