# Generated by Django 5.0 on 2024-01-15 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0010_vehiclelistingresult"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VehicleListingResult",
        ),
    ]
