# Generated by Django 5.0.1 on 2024-02-29 14:53

import base_app.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0015_notifications_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRentingRequests',
            fields=[
                ('reference_id', models.CharField(default=base_app.models.generate_uuid, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('data_generated_on', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.TextField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')])),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renting_requests', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renting_requests', to='base_app.vehicles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
