# Generated by Django 5.0.1 on 2024-02-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_vehiclerentingrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclerentingrequests',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='vehiclerentingrequests',
            name='start_date',
        ),
        migrations.AddField(
            model_name='vehiclerentingrequests',
            name='renting_period',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
