# Generated by Django 5.0.1 on 2024-03-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0017_remove_vehiclerentingrequests_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='price',
            field=models.FloatField(default=25000),
            preserve_default=False,
        ),
    ]
