# Generated by Django 5.0.1 on 2024-04-05 02:44

import base_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0018_vehicles_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VehicleRent',
            fields=[
                ('reference_id', models.CharField(default=base_app.models.generate_uuid, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('data_generated_on', models.DateTimeField(auto_now_add=True)),
                ('renting_period_remaining', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('rent_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.vehiclerentingrequests')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
