# Generated by Django 5.0.1 on 2024-04-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0019_vehicles_is_booked_vehiclerent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_redirect_link',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.IntegerField(choices=[(0, 'System'), (3, 'Request Result'), (4, 'Transaction'), (5, 'Transaction Request')], default=0),
        ),
    ]
