# Generated by Django 5.0.1 on 2024-04-05 03:02

import base_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0020_notifications_notification_redirect_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRequest',
            fields=[
                ('reference_id', models.CharField(default=base_app.models.generate_uuid, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('data_generated_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(-2, 'Failed'), (-1, 'Cancelled'), (0, 'Due'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Paid')], default=0)),
                ('renting_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.vehiclerentingrequests')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('reference_id', models.CharField(default=base_app.models.generate_uuid, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('data_generated_on', models.DateTimeField(auto_now_add=True)),
                ('pidx', models.CharField(max_length=50, unique=True)),
                ('expires_in', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(-2, 'Failed'), (-1, 'Cancelled'), (0, 'Due'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Paid')], default=0)),
                ('transaction_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_app.transactionrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
