# Generated by Django 5.0.1 on 2024-04-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0022_remove_notifications_notification_redirect_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclerentingrequests',
            name='renting_period',
            field=models.DateTimeField(),
        ),
    ]
