# Generated by Django 5.0.1 on 2024-04-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0023_alter_vehiclerentingrequests_renting_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclerent',
            name='renting_period_remaining',
        ),
    ]
