# Generated by Django 5.0.1 on 2024-04-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0025_vehiclerent_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerent',
            name='status',
            field=models.TextField(choices=[('EXPIRED', 'Expired'), ('EXTENDED', 'Extended'), ('ACTIVE', 'Active')], default='ACTIVE'),
            preserve_default=False,
        ),
    ]
