# Generated by Django 5.0 on 2024-04-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0026_vehiclerent_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationuser",
            name="profile_picture",
            field=models.ImageField(
                default="uploads/images/default_user_pp.jpg", upload_to="uploads/"
            ),
        ),
        migrations.AlterField(
            model_name="vehiclerent",
            name="status",
            field=models.TextField(
                choices=[
                    ("EXPIRED", "Expired"),
                    ("EXTENDED", "Extended"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                ]
            ),
        ),
    ]
