# Generated by Django 5.0 on 2024-04-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0027_alter_applicationuser_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicles",
            name="location_lat",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicles",
            name="location_lng",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
