# Generated by Django 5.0 on 2024-04-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_app", "0030_transactionrequest_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionrequest",
            name="total_price",
        ),
        migrations.AddField(
            model_name="transactionrequest",
            name="days",
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transactionrequest",
            name="price_per_day",
            field=models.FloatField(default=4000),
            preserve_default=False,
        ),
    ]
